name: ci-cpu
on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - Karthikg99-patch-1
  pull_request:
    branches:
      - main
permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v4

    - name: Caching dependencies
      uses: actions/cache@v3
      with:
        path: ${{env.pythonLocation}}
        key: ${{env.pythonLocation}}
        
    - name: install dependencies
      run: |
        pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu
        pip install git+https://github.com/pyg-team/pytorch_geometric.git
        pip install pyg-lib -f https://data.pyg.org/whl/torch-2.1.0+cpu.html
        git clone https://github.com/openai/triton.git;  
        cd triton;
        pip install ninja cmake wheel; # build-time dependencies
        pip install -e python
        cd ..;
        pip install .;
    
    - name: run test cases
      run: | 
        cd ./test;
        pytest
