name: ci-cpu
on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - Karthikg99-patch-1
  pull_request:
    branches:
      - main
permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: |
        pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu
        pip install git+https://github.com/pyg-team/pytorch_geometric.git
        pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.0.0+${CUDA}.html
        git clone https://github.com/openai/triton.git;  
        cd triton;
        sudo pip install ninja cmake wheel; # build-time dependencies
        sudo pip install -e python
        cd ..;
        pip install .;
    
    - name: run test cases
      run: | 
        cd ./test;
        pytest test_ops.py
