name: ci-cpu
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: |
        pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu
