name: Test-ci-cpu

run-name: Automated CI test

on:

  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  fasten-test:

    runs-on: self-hosted

    steps:
    
      - uses: actions/checkout@v4
      # - name : Install dependencies
      #   run: |
      #     pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
      #     git clone https://github.com/openai/triton.git;
      #     cd triton/python;
      #     pip install cmake; # build-time dependency
      #     pip install -e .
      #     cd ../..
      #     cd ./fasten
      #     pip install .
      
      - name: Run pytest
        run: |
          source ~/Accdl/accdl/bin/activate
          cd ./test
          pytest test_ops.py

        


name: ci-cpu
on: 
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: |
        pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu
        git clone https://github.com/openai/triton.git;
        cd triton/python;
        pip install cmake;
        pip install -e .;
        cd ../..;
        cd ./fasten;
        pip install .;
    
    - name: run test cases
      run: | 
        cd ./test;
        pytest
